apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "runote-backend.fullname" . }}-config
  namespace: default
data:
{{- range $key, $value := .Values.env.config }}
  {{ $key }}: "{{ $value }}"
{{- end }}