replicaCount: 1

fullnameOverride: runote-backend

image:
  repository: syuhei0519/runote-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

containerPort: 80

env:
  config:
    APP_NAME: "Laravel"
    APP_ENV: "dev"
    APP_DEBUG: "false"
    APP_URL: "https://runote.example.com"
    LOG_CHANNEL: "stack"
    LOG_LEVEL: "debug"
    DB_CONNECTION: "mysql"
    DB_HOST: "db"
    DB_PORT: "3306"
    DB_DATABASE: "runote"
    VITE_APP_NAME: "Laravel"
  secretRefName: "runote-backend-secrets"  # SealedSecretが生成する Secret名

ingress:
  enabled: true
  className: nginx
  host: runote.local     # ← ローカル用ドメインなど
  tls: false
  tlsSecret: runote-backend-tls
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
